### ISSUE TITLE
512px classjob icons

### ISSUE THREAD

**Issue by chasedream1129** [xivapi/classjob-icons#6]
From The Rising Stones, the official community by FFXIV Chinese version operator Shengqu Games
![image](https://github.com/xivapi/classjob-icons/assets/36710631/de782906-b384-436c-a7f5-60a74ce213a1)

https://ff14risingstones.web.sdo.com/pc/static/png/zjob0-34d06530.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob1-c5f08e11.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob2-34f62181.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob3-84e82229.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob4-020b4fae.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob5-447088c1.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob6-1844e481.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob7-e9f66fdc.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob8-0eea4ebd.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob9-5b9e394a.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob10-bef1fecd.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob11-0ad12702.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob12-a4316535.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob13-0ae79d7a.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob14-6b960327.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob15-f18b7a6a.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob16-c59bee46.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob17-2ffc39d5.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob18-4ed7fdd7.png
https://ff14risingstones.web.sdo.com/pc/static/png/zjob19-d0e832b9.png

**Comment by Simbiat** [comment]
I would wonder what is the original source of the icons. And also where other icons are? On which page can you see the screenshot you've shared? Is it something available only after registration (which seems to require some ID besides mobile phone).

**Comment by chasedream1129** [comment]
> I would wonder what is the original source of the icons. And also where other icons are? On which page can you see the screenshot you've shared? Is it something available only after registration (which seems to require some ID besides mobile phone).

![image](https://github.com/xivapi/classjob-icons/assets/36710631/66c1dd94-c9d0-4a26-bbb1-096cbbc19185)

From the character information page of The Rising Stones(Chinese version of The Lodestone). You must log in to the FFXIV China version account to use it. As the Chinese operator of FFXIV, I feel that their original source is the icon assets provided by Square Enix.
But the icons for crafting classes are just 64px base64 images.

**Comment by Simbiat** [comment]
What's the ID number they want for registration? Is it like Chinese ID? Or FFXIV character's ID?

**Comment by chasedream1129** [comment]
> What's the ID number they want for registration? Is it like Chinese ID? Or FFXIV character's ID?

It's Chinese ID. In China, when playing online games, you must submit identity information to verify whether you are an adult. Minors can only play for two hours on weekends.

**Comment by Simbiat** [comment]
I see. I would suggest you create a PR to update those icons, that we have, but if they are to be used, we probably would want someone to update the new ones as they arrive as well.

**Comment by chasedream1129** [comment]
I will try to update if there are new ones. Will you add these to https://xivapi.com/docs/Icons?

**Comment by ArcaneDisgea** [comment]
Completely missed some PRs here. Just merged them.

It is unlikely that these would be added to the icons page on the xivapi site because with the new [beta API](https://beta.xivapi.com) there is no such page.
