### ISSUE TITLE
Dawntrail

### ISSUE THREAD

**Issue by Fuitad** [xivapi/classjob-icons#8]
Heya! Any chance this will be updated to add the two new Dawntrail jobs, Viper and Pictomancer?

**Comment by justin-frenzel** [comment]
Would be great to get this added for Dawntrail. I use these icons for my own custom overlay plugin; been using placeholders for PCT and VPR for now.

**Comment by ArcaneDisgea** [comment]
Thanks @Simbiat for doing this. I was just getting around to it and noticed the PR.
